# ==============================================================================
# app.R
# ------------------------------------------------------------------------------
# Phase 5 -- the Shiny app skeleton for the Lottery Odds Simulator.
#
# This wires the four finished backend layers together behind a bslib
# page_sidebar() UI:
#
#   filters (sidebar) --> filter_games()                       [strategies.R]
#                     --> chosen strategy object                [strategies.R]
#                     --> strategy_distribution()                [strategies.R]
#                     --> simulate_sessions()  (seeded)          [simulate.R]
#                     --> build_metrics(..., price = strategy_expected_price())
#                                                                 [metrics.R]
#
# The pipeline is deliberately gated behind an actionButton ("Run simulation")
# via eventReactive(), NOT recomputed on every slider tick -- N x R can be up
# to millions of draws, so re-running on every input change would make the app
# feel broken. See R/app_helpers.R for the plain (non-reactive) glue functions
# that do the actual work; the server below is thin wiring + input validation
# around them, which also makes them independently unit-testable
# (tests/testthat/test-app.R exercises both the helpers directly and the
# reactive graph via shiny::testServer()).
#
# Phase 6 replaces the placeholder histogram with the real chart set from
# R/viz.R: fan chart, final-P&L histogram (with a log/winsorize toggle),
# dream-vs-reality, single-session play-by-play, and a gated leaderboard-vs-N
# small multiple. Every plotOutput() carries alt text generated by viz.R's
# matching viz_*_alt() function (accessibility), passed as a reactive-aware
# function to renderPlot(alt = ...).
# ==============================================================================

library(shiny)
library(bslib)
library(ggplot2)
library(scales)

# ------------------------------------------------------------------------------
# Startup (once, outside the server -- shared across all sessions):
#   1. source the five finished backend layers + the Phase 5 glue helpers.
#   2. load (or build, if the cache is absent) outcomes.rds / game_summary.rds.
#   3. compute the purchasable universe once, to seed the game-picker choices.
# ------------------------------------------------------------------------------
app_root <- getwd()

for (rel in c("R/data_prep.R", "R/simulate.R", "R/metrics.R",
              "R/strategies.R", "R/app_helpers.R", "R/viz.R", "R/narrative.R",
              "R/compare.R")) {
  source(file.path(app_root, rel))
}

app_data          <- load_app_data(app_root)   # builds the cache on first run
outcomes_full     <- app_data$outcomes
game_summary_full <- app_data$game_summary

# Purchasable universe, computed once, to seed the initial game-picker choices
# (before any sidebar filter has been touched).
purchasable_default <- tryCatch(
  filter_games(game_summary_full, purchasable = TRUE),
  error = function(e) game_summary_full
)

# ------------------------------------------------------------------------------
# UI-level run-cost ceiling. simulate_sessions() memory-chunks internally so it
# will not blow up, but an unbounded N x R can still take a long time and make
# an interactive app feel unresponsive -- so we cap it here and message the
# user rather than silently clamping (see validate_run_bounds()).
# ------------------------------------------------------------------------------
N_MIN <- 1L;  N_MAX <- 5000L
R_MIN <- 1L;  R_MAX <- 10000L
NR_MAX <- 5e6

# ------------------------------------------------------------------------------
# Leaderboard-vs-N small multiple (Phase 6): the "how does the ranking shift
# as N grows" chart needs a simulation PER (strategy x N) grid point, which is
# too heavy to recompute on every input tick like the main pipeline already
# is. It is wired behind its OWN actionButton ("Compute leaderboard") with a
# small FIXED N grid, a modest R, and a small fixed preset set (not the full
# custom-mix machinery) -- deliberately bounded so a click is a few seconds,
# not a rerun of the expensive main pipeline's N x R budget.
# ------------------------------------------------------------------------------
LEADERBOARD_N_GRID <- c(10L, 50L, 200L, 500L, 1000L, 2000L)
LEADERBOARD_R       <- 300L
LEADERBOARD_PRESETS <- c(
  "Cheapest"        = "cheapest",
  "Priciest"        = "priciest",
  "Best RTP"        = "best_rtp",
  "Worst RTP"       = "worst_rtp",
  "Biggest jackpot" = "biggest_jackpot"
)

# ------------------------------------------------------------------------------
# Compare mode (Phase 8): put strategies head-to-head FAIRLY. The compare
# pipeline (R/compare.R) drives every selected strategy with Common Random
# Numbers (the SAME uniform stream, via crn = seed) so observed differences are
# real, not sampling noise. It reuses the sidebar's N / R / seed / confidence so
# there is a single, clearly-surfaced seed control, and is gated behind its own
# "Run comparison" button (independent of the single-run "Run simulation").
# COMPARE_PRESETS are the config-free presets a user can tick to compare; the
# currently-configured sidebar strategy (single/custom included) can be added
# via a checkbox. The crossover small-multiple reuses the bounded leaderboard
# grid with the SHARED seed.
# ------------------------------------------------------------------------------
COMPARE_PRESETS <- c(
  "Always cheapest"  = "cheapest",
  "Always priciest"  = "priciest",
  "Best RTP"         = "best_rtp",
  "Worst RTP"        = "worst_rtp",
  "Biggest jackpot"  = "biggest_jackpot",
  "Random each play" = "random_each_play"
)

# Human-readable "Game (source, £price)" choices for the game-picker inputs.
game_choices <- function(gs) {
  if (is.null(gs) || nrow(gs) == 0L) return(character(0))
  labels <- sprintf("%s (%s, £%s)", gs$name, gs$source, format(gs$price))
  stats::setNames(gs$game_id, labels)
}

source_choices   <- sort(unique(game_summary_full$source))
category_choices <- sort(unique(game_summary_full$category))
price_bounds     <- range(game_summary_full$price, na.rm = TRUE)

strategy_choices <- c(
  "Single game"       = "single",
  "Always cheapest"   = "cheapest",
  "Always priciest"   = "priciest",
  "Best RTP"          = "best_rtp",
  "Worst RTP"         = "worst_rtp",
  "Biggest jackpot"   = "biggest_jackpot",
  "Random each play"  = "random_each_play",
  "Custom mix"        = "custom"
)

# ==============================================================================
# UI
# ==============================================================================
ui <- page_sidebar(
  title = "Lottery Odds Simulator",
  theme = bs_theme(version = 5, primary = "#2C3E50"),

  sidebar = sidebar(
    width = 360,

    h5("Game universe filters"),
    checkboxInput("purchasable_only",
                  "Purchasable only (exclude hidden / prohibited / off-sale)",
                  value = TRUE),
    checkboxInput("on_sale_only", "On sale only", value = FALSE),
    selectizeInput("source_filter", "Source", choices = source_choices,
                   selected = NULL, multiple = TRUE,
                   options = list(placeholder = "All sources")),
    selectizeInput("category_filter", "Category", choices = category_choices,
                   selected = NULL, multiple = TRUE,
                   options = list(placeholder = "All categories")),
    sliderInput("price_range", "Ticket price (£)",
                min = floor(price_bounds[1]), max = ceiling(price_bounds[2]),
                value = c(floor(price_bounds[1]), ceiling(price_bounds[2])),
                step = 0.5, pre = "£"),
    uiOutput("universe_status"),

    hr(),
    h5("Strategy"),
    selectInput("strategy_preset", "Strategy", choices = strategy_choices,
                selected = "cheapest"),
    conditionalPanel(
      condition = "input.strategy_preset == 'single'",
      selectizeInput("single_game", "Game",
                     choices = game_choices(purchasable_default))
    ),
    conditionalPanel(
      condition = "input.strategy_preset == 'custom'",
      selectizeInput("custom_games", "Games in the mix",
                     choices = game_choices(purchasable_default), multiple = TRUE),
      helpText("Set a relative weight for each selected game ",
               "(equal weight if left at the default)."),
      uiOutput("custom_weight_inputs")
    ),

    hr(),
    h5("Session design"),
    sliderInput("N", "N — tickets per session",
                min = N_MIN, max = N_MAX, value = 100, step = 1),
    sliderInput("R", "R — number of simulated sessions",
                min = R_MIN, max = R_MAX, value = 1000, step = 1),
    helpText(sprintf(
      "N x R is capped at %s draws per run to keep the app responsive.",
      format(NR_MAX, big.mark = ",", scientific = FALSE))),
    sliderInput("conf", "Confidence level", min = 0.5, max = 0.99,
                value = 0.90, step = 0.01),
    numericInput("seed", "Random seed", value = 42, min = 1, step = 1),

    hr(),
    h5("Display"),
    radioButtons(
      "pnl_transform", "Skewed-P&L axis transform",
      choices = c("None (linear GBP)" = "none",
                  "Winsorize (clip tails)" = "winsorize",
                  "Signed log" = "signed_log"),
      selected = "none"
    ),
    helpText("Applies to the P&L histogram and play-by-play charts. A ",
             "transformed axis distorts magnitudes -- see the axis label."),

    hr(),
    actionButton("run", "Run simulation", class = "btn-primary w-100")
  ),

  card(
    class = "border-primary mb-3",
    card_header("In plain English", class = "bg-primary text-white"),
    uiOutput("narrative_panel")
  ),

  navset_card_tab(
    nav_panel(
      "Fan chart",
      plotOutput("fan_plot", height = "480px"),
      p(class = "text-muted small",
        "Cumulative session P&L over plays. Nested bands are the checkpointed ",
        "percentile ribbon (outer = widest, inner = narrowest); solid line = ",
        "median; dashed red = mean. Mean and median diverging is the skew story.")
    ),
    nav_panel(
      "Distribution",
      plotOutput("dist_plot", height = "480px"),
      p(class = "text-muted small",
        "Distribution of final session P&L across all simulated sessions, with ",
        "break-even / mean / median / percentile markers.")
    ),
    nav_panel(
      "Dream vs reality",
      plotOutput("dream_plot", height = "440px"),
      p(class = "text-muted small",
        "The advertised full distribution (jackpot included) vs. the reality ",
        "of a session that does not hit the top prize -- almost every session.")
    ),
    nav_panel(
      "Play-by-play",
      plotOutput("pbp_plot", height = "440px"),
      p(class = "text-muted small",
        "One simulated session's cumulative P&L path, play by play, coloured ",
        "by win/loss.")
    ),
    nav_panel(
      "Leaderboard vs N",
      p(class = "text-muted small mt-2",
        sprintf(paste0(
          "Independent of the main run above -- sweeps P(profit) over a fixed ",
          "N grid (%s) at R = %s sessions/point across a fixed preset set, ",
          "over the CURRENTLY FILTERED game universe. Bounded on purpose so a ",
          "click is a few seconds, not a full pipeline run."),
          paste(format(LEADERBOARD_N_GRID, big.mark = ","), collapse = ", "),
          format(LEADERBOARD_R, big.mark = ","))),
      actionButton("run_leaderboard", "Compute leaderboard", class = "btn-secondary"),
      plotOutput("leaderboard_plot", height = "420px"),
      tableOutput("leaderboard_table")
    ),
    nav_panel(
      "Compare",
      p(class = "text-muted small mt-2",
        "Put strategies head-to-head. Every selected strategy is evaluated on ",
        strong("the same random draws (Common Random Numbers)"),
        " -- so the differences you see are real, not sampling noise. Uses the ",
        "sidebar's N / R / seed / confidence; change the seed to see a different ",
        "(equally fair) common draw. Gated behind its own button, independent of ",
        "\"Run simulation\"."),
      checkboxGroupInput("compare_presets", "Strategies to compare",
                         choices = COMPARE_PRESETS,
                         selected = c("cheapest", "biggest_jackpot"),
                         inline = TRUE),
      checkboxInput("compare_include_current",
                    "Also include the strategy configured in the sidebar",
                    value = FALSE),
      div(class = "d-flex gap-2 flex-wrap mb-2",
          actionButton("run_compare", "Run comparison", class = "btn-primary"),
          downloadButton("download_compare_csv", "Table (CSV)", class = "btn-secondary"),
          downloadButton("download_compare_png", "Distribution (PNG)", class = "btn-secondary")),
      plotOutput("compare_dist_plot", height = "420px"),
      plotOutput("compare_fan_plot", height = "420px"),
      p(class = "text-muted small mt-3",
        sprintf(paste0(
          "Low-N vs high-N crossover: P(profit) swept over a fixed N grid (%s) at ",
          "R = %s sessions/point, all strategies on the SHARED seed. Watch the ",
          "ranking flip -- at small N a higher-variance, worse-average game can ",
          "have the better break-even shot; at large N the mean/RTP ordering wins."),
          paste(format(LEADERBOARD_N_GRID, big.mark = ","), collapse = ", "),
          format(LEADERBOARD_R, big.mark = ","))),
      plotOutput("compare_crossover_plot", height = "380px"),
      tableOutput("compare_table")
    ),
    nav_panel(
      "Risk & engagement",
      verbatimTextOutput("headline_metrics")
    ),
    nav_panel(
      "Details",
      verbatimTextOutput("details_text")
    )
  )
)

# ==============================================================================
# Server
# ==============================================================================
server <- function(input, output, session) {

  is_error <- function(x) inherits(x, "error")

  # ---- Universe filters -> filtered game_summary (or a caught error) -------
  filtered_gs <- reactive({
    tryCatch(
      filter_games(
        game_summary_full,
        purchasable = isTRUE(input$purchasable_only),
        on_sale     = if (isTRUE(input$on_sale_only)) TRUE else NULL,
        price_min   = input$price_range[1],
        price_max   = input$price_range[2],
        category    = if (is.null(input$category_filter) ||
                          length(input$category_filter) == 0L) NULL
                      else input$category_filter,
        source      = if (is.null(input$source_filter) ||
                          length(input$source_filter) == 0L) NULL
                      else input$source_filter
      ),
      error = function(e) e
    )
  })

  # ---- Keep the game-picker choices in sync with the filtered universe -----
  observe({
    gs <- filtered_gs()
    choices <- if (is_error(gs)) character(0) else game_choices(gs)

    keep_single <- if (!is.null(input$single_game) && input$single_game %in% choices)
      input$single_game else if (length(choices)) choices[[1]] else character(0)
    updateSelectizeInput(session, "single_game", choices = choices, selected = keep_single)

    keep_custom <- intersect(input$custom_games, choices)
    updateSelectizeInput(session, "custom_games", choices = choices, selected = keep_custom)
  })

  output$universe_status <- renderUI({
    gs <- filtered_gs()
    if (is_error(gs)) {
      div(class = "text-danger small mt-1", conditionMessage(gs))
    } else {
      div(class = "text-muted small mt-1",
          sprintf("%d game(s) match the current filters.", nrow(gs)))
    }
  })

  # ---- Custom-mix: one weight numericInput per selected game ---------------
  output$custom_weight_inputs <- renderUI({
    ids <- input$custom_games
    if (is.null(ids) || length(ids) == 0L) {
      return(helpText("Select one or more games above."))
    }
    gs <- filtered_gs()
    tagList(lapply(ids, function(gid) {
      nm <- if (!is_error(gs)) gs$name[match(gid, gs$game_id)] else NA_character_
      lbl <- if (length(nm) == 0L || is.na(nm)) gid else nm
      numericInput(weight_input_id(gid), label = lbl, value = 1, min = 0, step = 0.5)
    }))
  })
  outputOptions(output, "custom_weight_inputs", suspendWhenHidden = FALSE)

  # ---- Gate the expensive pipeline behind "Run simulation" ------------------
  # WHY plain input$run (not a reactiveVal side-effect set inside the
  # eventReactive): a write to a reactiveVal made inside an eventReactive body
  # is not reliably observable afterwards on a path where that same body later
  # throws (validate() or a plain error) -- input$run itself has no such
  # wrinkle, so outputs gate on it directly.
  pipeline_result <- eventReactive(input$run, {
    gs <- filtered_gs()
    validate(need(!is_error(gs), if (is_error(gs)) conditionMessage(gs) else NULL))

    bound_msg <- validate_run_bounds(input$N, input$R, N_MAX, R_MAX, NR_MAX)
    validate(need(is.null(bound_msg), bound_msg))

    seed_val <- if (is.null(input$seed) || !is.finite(input$seed)) NULL else as.integer(input$seed)

    custom_ids <- input$custom_games
    custom_w   <- if (!is.null(custom_ids) && length(custom_ids) > 0L)
      collect_custom_weights(input, custom_ids) else NULL

    run_it <- function() {
      run_pipeline(
        gs = gs, outcomes = outcomes_full, preset = input$strategy_preset,
        single_game    = input$single_game,
        custom_games   = custom_ids,
        custom_weights = custom_w,
        N = input$N, R = input$R, seed = seed_val, conf = input$conf
      )
    }

    # Busy indicator while the run is in progress. WHY the inner tryCatch:
    # under shiny::testServer()'s MockShinySession, withProgress()/incProgress()
    # do not have real progress support and trip an empty "shiny.silent.error"
    # (the same condition class req() throws) purely as an artifact of the
    # mocked session -- NOT a validation failure from our own code (run_pipeline
    # only ever raises plain errors). Falling back to a plain call keeps the
    # pipeline testable headlessly while a real browser session still gets the
    # progress bar.
    result <- tryCatch(
      tryCatch(
        withProgress(message = "Running simulation", value = 0.1, {
          incProgress(0.2, detail = "Building strategy & distribution")
          out <- run_it()
          incProgress(0.7, detail = "Done")
          out
        }),
        shiny.silent.error = function(e) run_it()
      ),
      error = function(e) e
    )

    validate(need(!is_error(result), if (is_error(result)) conditionMessage(result) else NULL))
    # Best-effort toast; wrapped in try() because (like withProgress() above)
    # notifications are a noop-but-erroring artifact of testServer's
    # MockShinySession, and a failed toast should never fail the run.
    try(showNotification("Simulation complete.", type = "message", duration = 3),
        silent = TRUE)
    result
  }, ignoreInit = TRUE)

  not_run_msg <- "Configure your strategy and filters, then click \"Run simulation\"."

  # ---- A single extra session for the play-by-play chart --------------------
  # Cheap (O(N), no chunking -- see simulate_one_session()'s header), so this
  # is an ordinary reactive (not gated behind its own button): it only
  # recomputes when pipeline_result() changes, i.e. after a "Run simulation"
  # click. Seeded at seed + 1 (when a seed was supplied) so the single-session
  # replay is reproducible but not IDENTICAL to the first draw consumed by the
  # main sessions run.
  one_session <- reactive({
    res  <- pipeline_result()
    seed <- res$sim$seed
    seed <- if (is.null(seed)) NULL else as.integer(seed) + 1L
    simulate_one_session(res$dist, N = res$sim$N, seed = seed)
  })

  # ---- Phase 7 plain-English narrative ---------------------------------------
  # Prominent card above the tabbed chart/metric panels. Pure narrate_run()
  # (R/narrative.R) driven straight off the gated pipeline_result(); passing
  # `sim` upgrades the median/mean/interval sentences to exact empirical
  # figures off the raw session totals rather than the metrics bundle's
  # checkpoint grid (see narrate_run()'s header).
  output$narrative_panel <- renderUI({
    validate(need(isTRUE(input$run > 0), not_run_msg))
    res <- pipeline_result()
    sentences <- narrate_run(res$metrics, strategy = res$strategy,
                             sim = res$sim, conf = input$conf)
    tagList(lapply(sentences, function(s) p(s)))
  })

  # ---- Phase 6 chart outputs -------------------------------------------------
  output$fan_plot <- renderPlot({
    validate(need(isTRUE(input$run > 0), not_run_msg))
    res <- pipeline_result()
    viz_fan_chart(res$sim, title = sprintf("Fan chart — %s", res$strategy$label))
  }, alt = function() {
    if (!isTRUE(input$run > 0)) return(not_run_msg)
    viz_fan_chart_alt(pipeline_result()$sim)
  })

  output$dist_plot <- renderPlot({
    validate(need(isTRUE(input$run > 0), not_run_msg))
    res <- pipeline_result()
    viz_pnl_hist(res$sim, transform = input$pnl_transform,
                title = sprintf("Final session P&L — %s", res$strategy$label))
  }, alt = function() {
    if (!isTRUE(input$run > 0)) return(not_run_msg)
    viz_pnl_hist_alt(pipeline_result()$sim)
  })

  output$dream_plot <- renderPlot({
    validate(need(isTRUE(input$run > 0), not_run_msg))
    res <- pipeline_result()
    viz_dream_vs_reality(res$metrics, title = sprintf(
      "Dream vs reality — %s", res$strategy$label))
  }, alt = function() {
    if (!isTRUE(input$run > 0)) return(not_run_msg)
    viz_dream_vs_reality_alt(pipeline_result()$metrics)
  })

  output$pbp_plot <- renderPlot({
    validate(need(isTRUE(input$run > 0), not_run_msg))
    res <- pipeline_result()
    viz_play_by_play(one_session(), price = res$metrics$meta$price,
                     transform = input$pnl_transform,
                     title = sprintf("Play-by-play — %s", res$strategy$label))
  }, alt = function() {
    if (!isTRUE(input$run > 0)) return(not_run_msg)
    viz_play_by_play_alt(one_session(), price = pipeline_result()$metrics$meta$price)
  })

  # ---- Leaderboard vs N (gated behind its own button; see LEADERBOARD_*
  # constants above for the bounded grid/preset set) --------------------------
  leaderboard_not_run_msg <- "Click \"Compute leaderboard\" to sweep P(profit) vs N across strategies."

  leaderboard_result <- eventReactive(input$run_leaderboard, {
    gs <- filtered_gs()
    validate(need(!is_error(gs), if (is_error(gs)) conditionMessage(gs) else NULL))

    seed_val <- if (is.null(input$seed) || !is.finite(input$seed)) NULL else as.integer(input$seed)

    parts <- lapply(names(LEADERBOARD_PRESETS), function(nm) {
      preset <- LEADERBOARD_PRESETS[[nm]]
      strat  <- tryCatch(build_strategy(preset, gs, outcomes_full), error = function(e) e)
      if (is_error(strat)) return(NULL)
      dist <- strategy_distribution(strat, outcomes_full)
      d <- leaderboard_series(dist, N_grid = LEADERBOARD_N_GRID, metric = "p_profit",
                              R = LEADERBOARD_R, seed = seed_val)
      cbind(strategy = nm, d)
    })
    parts <- parts[!vapply(parts, is.null, logical(1))]
    validate(need(length(parts) > 0,
                  "No presets could be built under the current filtered universe."))
    do.call(rbind, parts)
  }, ignoreInit = TRUE)

  output$leaderboard_plot <- renderPlot({
    validate(need(isTRUE(input$run_leaderboard > 0), leaderboard_not_run_msg))
    viz_leaderboard_vs_n(leaderboard_result())
  }, alt = function() {
    if (!isTRUE(input$run_leaderboard > 0)) return(leaderboard_not_run_msg)
    viz_leaderboard_vs_n_alt(leaderboard_result())
  })

  output$leaderboard_table <- renderTable({
    validate(need(isTRUE(input$run_leaderboard > 0), leaderboard_not_run_msg))
    viz_leaderboard_table(leaderboard_result())
  })

  # ---- Compare mode (Phase 8): CRN-driven head-to-head ----------------------
  # Gated behind its OWN button, independent of "Run simulation". Builds each
  # selected strategy over the currently filtered universe, then run_compare()
  # drives them all on the SAME uniform stream (crn = seed) for a fair compare.
  compare_not_run_msg <- "Pick at least two strategies and click \"Run comparison\"."

  compare_result <- eventReactive(input$run_compare, {
    gs <- filtered_gs()
    validate(need(!is_error(gs), if (is_error(gs)) conditionMessage(gs) else NULL))

    bound_msg <- validate_run_bounds(input$N, input$R, N_MAX, R_MAX, NR_MAX)
    validate(need(is.null(bound_msg), bound_msg))

    # Build the config-free presets the user ticked.
    strats <- list()
    for (p in input$compare_presets) {
      s <- tryCatch(build_strategy(p, gs, outcomes_full), error = function(e) NULL)
      if (!is.null(s)) strats[[length(strats) + 1L]] <- s
    }
    # Optionally add the sidebar-configured strategy (single/custom supported).
    if (isTRUE(input$compare_include_current)) {
      custom_ids <- input$custom_games
      custom_w   <- if (!is.null(custom_ids) && length(custom_ids) > 0L)
        collect_custom_weights(input, custom_ids) else NULL
      cur <- tryCatch(build_strategy(
        input$strategy_preset, gs, outcomes_full,
        single_game = input$single_game,
        custom_games = custom_ids, custom_weights = custom_w),
        error = function(e) NULL)
      if (!is.null(cur)) strats[[length(strats) + 1L]] <- cur
    }

    seed_val <- if (is.null(input$seed) || !is.finite(input$seed)) 1L else as.integer(input$seed)

    res <- tryCatch(
      run_compare(strats, outcomes_full, N = input$N, R = input$R,
                  seed = seed_val, conf = input$conf),
      error = function(e) e)
    validate(need(!is_error(res), if (is_error(res)) conditionMessage(res) else NULL))
    res
  }, ignoreInit = TRUE)

  # Crossover small-multiple: the compared strategies swept over the bounded
  # leaderboard N grid on the SHARED seed (its own light sweep -- see
  # run_compare_leaderboard()).
  compare_crossover <- reactive({
    res <- compare_result()
    strats <- lapply(res$per, function(p) p$strategy)
    run_compare_leaderboard(strats, outcomes_full, N_grid = LEADERBOARD_N_GRID,
                            metric = "p_profit", R = LEADERBOARD_R, seed = res$seed)
  })

  output$compare_dist_plot <- renderPlot({
    validate(need(isTRUE(input$run_compare > 0), compare_not_run_msg))
    viz_compare_dist(compare_result(), transform = input$pnl_transform)
  }, alt = function() {
    if (!isTRUE(input$run_compare > 0)) return(compare_not_run_msg)
    viz_compare_dist_alt(compare_result())
  })

  output$compare_fan_plot <- renderPlot({
    validate(need(isTRUE(input$run_compare > 0), compare_not_run_msg))
    viz_compare_fan(compare_result())
  }, alt = function() {
    if (!isTRUE(input$run_compare > 0)) return(compare_not_run_msg)
    viz_compare_fan_alt(compare_result())
  })

  output$compare_crossover_plot <- renderPlot({
    validate(need(isTRUE(input$run_compare > 0), compare_not_run_msg))
    viz_leaderboard_vs_n(compare_crossover(),
                         title = "P(profit) vs N -- the low-N vs high-N crossover")
  }, alt = function() {
    if (!isTRUE(input$run_compare > 0)) return(compare_not_run_msg)
    viz_leaderboard_vs_n_alt(compare_crossover())
  })

  output$compare_table <- renderTable({
    validate(need(isTRUE(input$run_compare > 0), compare_not_run_msg))
    compare_table_display(compare_result())
  })

  # ---- Export: comparison table as CSV, distribution overlay as PNG ---------
  output$download_compare_csv <- downloadHandler(
    filename = function() sprintf("lottery_compare_%s.csv", Sys.Date()),
    content = function(file) {
      utils::write.csv(compare_result()$table, file, row.names = FALSE)
    }
  )
  output$download_compare_png <- downloadHandler(
    filename = function() sprintf("lottery_compare_dist_%s.png", Sys.Date()),
    content = function(file) {
      ggplot2::ggsave(file, viz_compare_dist(compare_result(),
                                             transform = input$pnl_transform),
                      width = 9, height = 5.5, dpi = 120)
    }
  )

  output$headline_metrics <- renderPrint({
    validate(need(isTRUE(input$run > 0), not_run_msg))
    res    <- pipeline_result()
    m      <- res$metrics
    totals <- res$sim$totals

    cat("STRATEGY\n")
    cat(sprintf("  %s\n", res$strategy$label))
    cat(sprintf("  %s\n\n", res$strategy$description))

    cat("SESSION DESIGN\n")
    cat(sprintf("  N (tickets/session): %s   R (sessions): %s   seed: %s\n",
                format(m$meta$N, big.mark = ","), format(m$meta$R, big.mark = ","),
                if (is.null(m$meta$seed)) "none" else m$meta$seed))
    cat(sprintf("  Expected price/play: £%.2f   Expected stake/session: £%.2f\n\n",
                m$meta$price, m$meta$total_stake))

    cat("SESSION P&L\n")
    cat(sprintf("  Mean:   £%.2f\n", mean(totals)))
    cat(sprintf("  Median: £%.2f\n", stats::median(totals)))
    cat(sprintf("  P(profit):               %.1f%%\n", 100 * m$risk$p_profit))
    cat(sprintf("  P(break-even or better): %.1f%%\n", 100 * m$risk$p_breakeven))
    cat(sprintf("  %.0f%% VaR (loss):                £%.2f\n",
                100 * (1 - m$risk$alpha), m$risk$var$loss))
    cat(sprintf("  %.0f%% Expected shortfall (loss):  £%.2f\n\n",
                100 * (1 - m$risk$alpha), m$risk$es$loss))

    cat("ENGAGEMENT\n")
    cat(sprintf("  Expected wins/session: %.2f  (P(a given play wins) = %.1f%%)\n",
                m$engagement$expected_wins, 100 * m$engagement$p_win))
    cat(sprintf("  Longest losing streak — median: %d plays, 95th pct: %d plays\n",
                round(m$streak$median), round(m$streak$quantiles[["p95"]])))
  })

  output$details_text <- renderPrint({
    validate(need(isTRUE(input$run > 0), not_run_msg))
    res   <- pipeline_result()
    strat <- res$strategy

    cat(sprintf("<lottery_strategy> %s [%s]\n", strat$label, strat$type))
    cat(sprintf("id: %s\n", strat$id))
    cat(sprintf("%s\n\n", strat$description))

    cat("Games and weights:\n")
    for (i in seq_along(strat$game_ids)) {
      cat(sprintf("  %-45s w=%.4f  £%s\n",
                  strat$game_ids[i], strat$weights[i], format(strat$prices[i])))
    }

    sp <- res$spend
    cat("\nRealised spend framing (fixed N):\n")
    cat(sprintf("  Expected spend: £%.2f (sd £%.2f)%s\n",
                sp$expected_spend, sp$spend_sd,
                if (sp$variable_spend)
                  "  [mixed ticket prices — spend varies session to session]" else ""))

    a <- res$analytical
    cat("\nAnalytical reference (Normal/CLT approximation):\n")
    cat(sprintf("  Mean: £%.2f   %d%% CI: [£%.2f, £%.2f]\n",
                a$mean, round(a$conf * 100), a$ci_lo, a$ci_hi))
    cat("  (unreliable at small N for skewed/jackpot games — see simulate.R header)\n")
  })
}

shinyApp(ui = ui, server = server)
